on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn prettier --check .

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: yarn test:cypress:run

  deploy:
    if: github.event_name	== 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx vercel --confirm --token $VERCEL_TOKEN -S $VERCEL_SCOPE -n $VERCEL_NAME
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_NAME: ${{ secrets.VERCEL_NAME }}

  deployToProduction:
    if: github.event_name	== 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [cypress]
    steps:
      - uses: actions/checkout@v2
      - run: npx vercel --prod --confirm --token $VERCEL_TOKEN -S $VERCEL_SCOPE -n $VERCEL_NAME
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_NAME: ${{ secrets.VERCEL_NAME }}
